services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - '32768:${DB_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: -p 32768

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5454:5454/tcp"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454

volumes:
  data: {}
